### PR TITLE
Base station 2015

### PR DESCRIPTION
**Pull request by justbuchanan**
Here's my first attempt at a simple pcb for the base station (see #15 ).  I don't entirely know what I'm doing here, so if you can take a look and give me your tips, tricks, and criticisms, that would be great!  Here are screenshots of the schematic and board:

schematic
board

Questions/todos:

- [x] double-check pad size for radio board connector
- [ ] select hole size for pcb mounting
- [x] double-check connector orientation relative to radio board
- [x] measure size of radio board and adjust footprint/symbol
- [x] how should the two antennas be positioned to reduce interference?
- [x] @barulicm, any changes to the pcb that would make it easier to print a box for?  I'm thinking we'll want to keep the mbed's LEDs visible and button accessible, so I don't know how much we can cover on top
- [x] fix wire routing overlaps
- [ ] adjust trace sizes/spacing for manufacturing
- [x] holes for radio board connector
- [x] ground plane on top and bottom
- [x] check usb connector - the one at the shop doesn't require mounting holes, but the one in eagle does
- [ ] make sure vias are placed with plenty of clearance.  Also best to make them large since the GVU circuit mill isn't perfect at lining up top and bottom layers.
- [x] fix pin labels for radio connector

cc @jjones646 @barulicm @ryanstrat

### CODE REVIEW

**Comment by ryanstrat** [comment]
If you're planning on etching this in house, You'll want to make your traces wider (0.3" or so) you want to leave lots of clearance from vias as well.

There's also considerable routing weirdness near the radio connectors. It looks like traces are travelling over pads.

**Comment by barulicm** [comment]
@ryanstrat Haven't looked at the design yet, but we're going to try to use the GVU mill assuming it's functional and Scott's available next week.

**Comment by justbuchanan** [comment]
Sounds good.  I'll have to tailor it to what the GVU machine can do or what our etching skills can handle.

Good call - I used the autorouter tool, so I don't know how that happened.  Maybe something when I changed the part file for the connector.  I'll look into it.

**Comment by jjones646** [comment]
Autorouter?
wut

- Make a ground plane on the top + bottom
- The radio board's header needs 2 small holes in the footprint
- The mounting holes are pretty close to the edge of the pcb
- larger traces

**Comment by ryanstrat** [comment]
@barulicm I was going to look up the model of the PCB mill and get @justbuchanan some suggested tolerances, but the GVU prototyping webpages are all empty

**Comment by ryanstrat** [comment]
Also @justbuchanan Autorouter: not even once.

Thank you for making this year's example for Electrical Training of why we don't use autorouter.

**Comment by barulicm** [comment]
@ryanstrat I'll look at it next time I'm in the basement this afternoon

**Comment by ryanstrat** [comment]
@danbudanov ^see above images for Electrical Training.

**Comment by jjones646** [comment]
8mil if no one has broken the bit lately...

http://gritslab.gatech.edu/Pickem/projects/prototyping

**Comment by justbuchanan** [comment]
Hahaha darn, I thought I was getting away without having to draw all those wires by hand...

**Comment by justbuchanan** [comment]
@jjones646 Do you think there's any better positioning of the radios to minimize interference or is it good enough as-is?

**Comment by ryanstrat** [comment]
If you are OK with a slightly bigger board, you could rotate the mbed 90 degrees.

**Comment by justbuchanan** [comment]
That's true - I'll take a look.  Do you think having the mbed rotated would help much?

**Comment by justbuchanan** [comment]
Also, I'm looking at the [datasheet](http://portal.fciconnect.com/Comergent//fci/drawing/95781.pdf) for the connector and I don't know how to parse it... Which number is the drill size?

2016-06-16-161026_414x151_scrot

**Comment by ryanstrat** [comment]
The hole should have a diameter of .052

**Comment by justbuchanan** [comment]
Where can I get a license for eagle?

**Comment by ryanstrat** [comment]
"Owncloud"


Ryan Strat
ryan@str.at
(678) 517-3393
RoboJackets | President
Georgia Institute of Technology

**Comment by jjones646** [comment]
I forget the exact number, but it's something around 9 or 10 inches before you'd see a small benefit...maybe. So it's good enough as is.

**Comment by justbuchanan** [comment]
After actually measuring the radio boards, I realized they were a good bit bigger than what I sketched out earlier.  Here's an updated layout (not routed or anything yet).

2016-06-16-171011_452x690_scrot

**Comment by justbuchanan** [comment]
I realized I was using autorouter on "low effort" before.  I tried bumping it up and I don't see any large issues.  I may manually route to pretty it up a bit though.

2016-06-16-174620_535x762_scrot

**Comment by jjones646** [comment]
Vias close to the pins like this will make soldering a pain. Vias in general are going to be a hassle because metal has to go in the hole somehow - idk what the gvu lab has for this.
vias

And in general, the larger clearances you can route, the better. For this, you could easily have 16+ clearance all around. The ground planes are super important too because the circuit mill will take 50x longer without them.

**Comment by justbuchanan** [comment]
Sounds good - I'll be sure and move the vias away from things/eachother.  I haven't messed with trace sizes and spacing just yet - waiting to find out what GVU has so I can set those parameters in Eagle.

**Comment by jjones646** [comment]
btw, I'm fairly certain some of the pins on the radio connector are wrong. I haven't looked to confirm anything, but something seems off slightly

**Comment by justbuchanan** [comment]
Ok, I'll make sure and double-check all those.  Do you have a pinout for it?  I was going by the CC Debugger's pin layout:

CC Debugger

**Comment by justbuchanan** [comment]
Here's my part's symbol:

2016-06-16-223445_474x420_scrot

**Comment by jjones646** [comment]
I'll put the pinout on here in a bit. It's different than that.

**Comment by jjones646** [comment]
radio-header

**Comment by justbuchanan** [comment]
Here's the final board:

board-final

**Comment by justbuchanan** [comment]
Should I move this to archive-pcb?  I think the design is decent, but it probably won't be used for anything.

**Pull request closed without merging**
